---
namespace: oriolrius
name: netmaker
version: 1.0.1
readme: README.md

authors:
  - Oriol Rius <oriol@example.com>

description: >-
  Comprehensive Ansible collection for managing Netmaker WireGuard mesh networks
  and external client devices via API. Features idempotent operations, auto-discovery
  of ingress gateways, and modern tooling. Perfect for IoT devices, edge computing,
  and secure remote access.

license:
  - GPL-3.0-or-later

tags:
  - netmaker
  - wireguard
  - vpn
  - networking
  - mesh
  - iot
  - security
  - infrastructure
  - automation
  - api

dependencies: {}

repository: https://github.com/oriolrius/netmaker-ansible-automation
documentation: https://github.com/oriolrius/netmaker-ansible-automation/blob/main/README.md
homepage: https://github.com/oriolrius/netmaker-ansible-automation
issues: https://github.com/oriolrius/netmaker-ansible-automation/issues

build_ignore:
  - .git
  - .gitignore
  - .env
  - .env.example
  - '*.pyc'
  - '*.pyo'
  - '*.log'
  - __pycache__
  - .venv
  - venv
  - '*.egg-info'
  - dist
  - build
  - library
  - playbooks
  - justfile
  - uv.lock
  - pyproject.toml
